services:
  gplvm_dinov3:
    image: dinov3:latest
    container_name: gplvm_dinov3
    working_dir: /workspace
    volumes:
      - ./:/workspace
      # The repo directory is now strictly mapped so weights aren't downloaded every time
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    # Keep container alive for execution via `docker exec`
    command: tail -f /dev/null

  gplvm_gpytorch:
    build:
      context: .
      dockerfile: docker/gpytorch/Dockerfile
    image: gplvm_gpytorch_image:latest
    container_name: gplvm_gpytorch
    working_dir: /workspace
    volumes:
      - ./:/workspace
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    command: tail -f /dev/null
